version: '3.7'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    restart: on-failure
    ports:
      - "443:443"
    networks:
      - inception_network
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: on-failure
    ports:
      - 3306
    networks:
      - inception_network

networks:
  inception_network:
    name: inception_network

volumes:
  mariadb_data:
    name: mariadb_data
  wordpress_data:
    name: wordpress_data

