version: '3.7'

services:

#  nginx:
#    container_name: nginx
#    depends_on:
#      - wordpress
#    build: ./requirements/nginx
#    image: nginx
#    restart: on-failure
#    ports:
#      - "443:443"
#    networks:
#      - inception_network

#  wordpress:
#    container_name: wordpress
#    depends_on:
#      - mariadb
#    build: ./requirements/wordpress
#    image: wordpress
#    restart: on-failure
#    env_file: .env
#    volumes:
#      - /home/aarrien/data/wordpress:/var/www/wordpress
#    networks:
#      - inception_network

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: on-failure
    env_file: .env
    volumes:
      - /home/aarrien/data/mariadb:/var/lib/mysql
    networks:
      - inception_network

networks:
  inception_network:
    name: inception_network
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb_data
    driver_opts:
      type: volume
      device: /home/aarrien/data/mariadb
  wordpress_data:
    name: wordpress_data
    driver_opts:
      type: volume
      device: /home/aarrien/data/wordpress

